### ISSUE TITLE
Battle 2k3: Item animations

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/Player#1269]
![sin titulo](https://user-images.githubusercontent.com/1331889/30932985-7f425d80-a3c9-11e7-8200-a87cd61ecf90.png)

~~wtf is CBA~~

Weapon CBA:

- [x] Show the right handed battle weapon in battle (#2510)
- [x] Show left handed (TODO: Both handed?) (#2510)
- [x] Movement (#2503):
  - [x] No Movement: Use the skill without moving.
  - [x] Step Forward: Step forward, then use the skill.
  - [x] Jump Forward: Jump forward, then use the skill.
  - [x] Move to Enemy: Move in front of the enemy, then use the skill.
- [x] Attack Count: How often to swing the weapon, just optical. Not for animations (#2399)
- [x] CBA Weapon (#2510)
- [x] Afterimage yes/no "Choose from the dropdown menu whether an afterimage should be shown when the actor is moving during skill usage. If No movement was selected, there is no need to specify this. (#2538)

Battle Animation CBA:
- [x] Battle animation (#2510)

Ranged CBA:
- [x] "Use" checkbox (#2515)
- [ ] Ranged Path
  - [x] Dagger "fly in a straight line like a knife" (#2515)
  - [ ] Boomerang "Follow an elliptic path"
- [ ] Ranged Attack range
  -  [x] Single Enemy (#2515)
  - [x] Center (#2537)
  - [X] All Enemies (#2537)
  - [ ] Attack in Sequence
- [x] Flying speed (#2515):
   - [x] Slow
   - [x] Normal
   - [x] Fast

32 different battle weapon types can be configured (Animation 2 tab). Each item has one of these types with corresponding animation. The graphic used is per battler.

~~Open questions:
Can this be used together with "Battle animation" battlers? Based on the GUI: No~~

**Comment by CherryDT** [comment]
CBA = Character Battle Animation

**Comment by fmatthew5876** [comment]
CBA Movement details
=======================

Here some details about how CBA movement works. More investigation and testing is needed.

Actor::UpdateBattle 004BBD7C
```
if (hidden) return;
if (battle event is waiting for wait command or waiting for "wait for key" (from wait command, not keyinputproc)) return;

damagePopupTimer -= 4
framecounter++
framecounter++ //Not a typo, this really happens twice?!

// Handle victory conditions
// Handle row command placement

// Handle weapon attacks

```


Actor::UpdateBattlePositionToDestination: 004BAE58
framecounter is set to 0 before this is called
```
yjump = 0
if (move_type == jump) {
  yjump = sin(((framecounter << 7) / 25 * 16.0) / 256.0)
}
if (framecounter < 25) {
  x = origin_x + framecounter * (dest_x - origin_x) / 25;
  y = origin_y + framecounter * (dest_y - origin_y) / 25 - truncate(yjump)
}
if (framecounter > 25) {
  x = dest_x
  y = dest_y
  framecounter = 0
 actorAnimationFrame = 0
}
``

UpdateBattlePositionToOrigin: 004BAF04

framecounter is set to 25 before this is called
```
yjump = 0
if (move_type == jump) {
  yjump = sin(((framecounter << 7) / 25 * 16.0) / 256.0)
}
if (framecounter > 25) {
  x = origin_x + (50 - framecounter) * (dest_x - origin_x) / 25;
  y = origin_y + (50 - framecounter) * (dest_y - origin_y) / 25 + truncate(yjump)
}
if (framecounter > 50) {
  x = dest_x
  y = dest_y
  framecounter = 0
 actorAnimationFrame = 0
}
``

**Comment by Ghabry** [comment]
@rueter37 could you please mention in all CBA related PRs which checkboxes of this issue it resolves? Thanks.
Helps with progress tracking.

**Comment by rueter37** [comment]
PR #2503 handles all movement related checkboxes.

**Comment by rueter37** [comment]
The "Attack Count" checkbox is already resolved by @fmatthew5876's battle system rewrite (PR #2399).

**Comment by Ghabry** [comment]
That CBA Animation box is also used by "Super Mario RPG - The seven sages". 
[Save02.zip](https://github.com/EasyRPG/Player/files/6300100/Save02.zip)

Enter mushroom pass 2 (you stand on it in Save02), then attack a goomba. The standard animation is "Jump boots" because of the equipped item.

**Comment by Ghabry** [comment]
I finally saw what this "After Image" option is by recording a video:
This is about rendering a trail, like you know from this mouse trail option on windows.
Here on a white background for figuring out the opacity:

![trail](https://user-images.githubusercontent.com/1331889/115140575-369fff00-a038-11eb-8fa4-207b818837f8.png)
![trail2](https://user-images.githubusercontent.com/1331889/115140574-369fff00-a038-11eb-8946-2fc1ae7c2c02.png)

**Comment by CherryDT** [comment]
Uhm, yes, that's what you call an afterimage in animation :D

**Comment by Ghabry** [comment]
okay at least I can still rant about the UI which uses a [X] Yes [ ] No exclusive radiobox for this. Yes-No-Questions should be a checkbox ;)

**Comment by rueter37** [comment]
I'm sorry for the next disappointment but implementing the CBA ranged weapons is above my skill level. It is harder than it looks. The two biggest offenders are the "Boomerang" path and the "Attack in Sequence" range. The former requires greater changes in the battle state machine because the battle animation is played in the middle of the ranged weapon animation. And the latter really messes up the targeting: It changes a single target weapon to an all targets weapon. Every enemy is attacked once in sequence. It gets worse if the "Attack all enemies" item flag is set, then the entire enemy party is attacked times the enemy party size. Trying to implement these badly messes up the code.

**Comment by rueter37** [comment]
For a change some good news: At least implementing single target CBA ranged weapons which travel a straight path is possible, see #2515.

**Comment by Ghabry** [comment]
I noticed now some new asshole Ui design here:

![Screenshot_20210502_153048-fs8](https://user-images.githubusercontent.com/1331889/116814959-97145d80-ab5b-11eb-81a7-790811bb27b3.png)

When the CBA type is "Use ranged" and confirm the setting it will alter the "Attack all enemies at the same time" checkbox state:

- Single Enemy and Attack in sequence: Check is removed
- Center and All Enemies: Check is added

Of course you can still alter the checkbox:

- Single Enemy:
  - w/o "Attack all": Single bow attacking at one enemy
  -"Attack all": The selected enemy is attacked by the arrow but all take damage
- Center:
  - w/o "Attack all": _Broken_ behaves like "Single Enemy"
  - "Attack all": Arrow flies into the center, all take damage
- All Enemies:
  - w/o "Attack all": _Broken_ behaves like "Single Enemy"
  -  "Attack all": Arrow flies at all enemies, all take damage
- Attack in Sequence:
  - w/o "Attack all": They are attacked one-by-one and take damage
  -  "Attack all": They are attacked one-by-one but _all_ take damage (totally op must be nerfed)

**Comment by Ghabry** [comment]
I bet there is some minor difference but this "attack x times" stuff looks like "enable combo" to me so maybe just use the same well-tested code path here.

**Comment by Ghabry** [comment]
The boomerang type has two differences:

- It moves back (the dagger type only moves forward)
- The Y value is on some kind of sinus curve
- The X path is the same as for the dagger

So the hard part is figuring out all Y-Values (does it depend on the enemy height?)

**Comment by Ghabry** [comment]
To make the issue tracking easier I will close this one and open a new one for the ranged CBA
