### ISSUE TITLE
Multi-column UI windows should have a gap between the selector

### ISSUE THREAD

**Issue by fmatthew5876** [EasyRPG/Player#2216]
![Untitled](https://user-images.githubusercontent.com/1198466/81994538-168ce200-9616-11ea-873b-2509edb6bd89.png)

Using the same game in both Player and RPG_RT. Notice the difference in width of the selector bar. In RPG_RT, if you flip the bar left and right you'll see a gap in the middle.

If Player, there is no gap. Our bar covers exactly half of the window size.

There are a lot of other small differences here which I think are just due to fonts?

This also lists several UI tweaks, but I'm not sure how many are due to font differences vs actual pixel positioning. 

- [x] Fix selector bar in item / skills #2313
- [ ] Fix face position in main menu. Note differences between 2k / 2k3 and party target window
- [x] Skill window costs text is off by 2 pixels #2313
- [x] Save file name is wrong. Half space between filetext and number #2313
- [x] Save file selector bar is too short #2313
- [ ] Check all other screens for position fixes

#2313

**Comment by carstene1ns** [comment]
I think we do not really need to be pixel perfect here, because of the font, the margin is simply different.
If add the gap, needs repositioning the texts and may cut off long lines or such.

**Comment by Ghabry** [comment]
Kinda related: There is a reverse engenering framework for python (using js for scripting) called https://frida.re. This allows arbitrary function hooking anywhere independent of the calling convention. Saw this used by one of the Google Project Zero members (taviso).

Never used this before but here is a simple example hooking ExtTextOutA:
```
frida-trace -n RPG_RT.exe -i ExtTextOutA -X gdi32full.dll

onEnter: function (log, args, state) {
  log("ExtTextOutA(" + args[1] + ", " + args[2] + ", " + args[5].readAnsiString() + ")");
  args[5].writeAnsiString("X");
},
```

![Unbenannt-fs8](https://user-images.githubusercontent.com/1331889/82121897-ac4c7c80-9790-11ea-8872-72d94ea7389f.png)

**Comment by fmatthew5876** [comment]
![equip](https://user-images.githubusercontent.com/1198466/82123027-21a25800-9765-11ea-9318-1c22d15406ce.png)
![exit](https://user-images.githubusercontent.com/1198466/82123028-223aee80-9765-11ea-87fb-c87b6e12d050.png)
![file](https://user-images.githubusercontent.com/1198466/82123030-22d38500-9765-11ea-85ec-eae6a23891d4.png)
![item](https://user-images.githubusercontent.com/1198466/82123031-22d38500-9765-11ea-8324-28ce47075e35.png)
![main](https://user-images.githubusercontent.com/1198466/82123032-22d38500-9765-11ea-8699-30ff72a47121.png)
![party](https://user-images.githubusercontent.com/1198466/82123033-22d38500-9765-11ea-9f7c-f75f03b2fd3b.png)
![party_target](https://user-images.githubusercontent.com/1198466/82123035-22d38500-9765-11ea-82c6-3c60564b6c24.png)
![skill](https://user-images.githubusercontent.com/1198466/82123036-22d38500-9765-11ea-9959-c67ceef844d4.png)
![status](https://user-images.githubusercontent.com/1198466/82123037-236c1b80-9765-11ea-8b8c-4752ffe4aa20.png)
![Pixel](https://user-images.githubusercontent.com/1198466/82123046-2f57dd80-9765-11ea-8d34-3ea92d2d9251.png)

**Comment by Ghabry** [comment]
Great now you just need a "X" in the Player font that looks like this X and we can do comparisons :)

**Comment by fdelapena** [comment]
An extracted EXFONT resource would help testing this without needing to change Player fonts.

**Comment by rueter37** [comment]
I have deleted my old "fixes-0.6.1" and "fixes-0.6.2" branches because they are obsolete now and the relevant changes have been already PR'd or merged in. I'm writing this comment because the opening post has a link to the deleted branch.

**Comment by Ghabry** [comment]
Maybe useful:
This renders a X looking like the RPG_RT one:

```
diff --git a/src/bitmapfont_ttyp0.h b/src/bitmapfont_ttyp0.h
index 550199aaf..bc4578d4d 100644
--- a/src/bitmapfont_ttyp0.h
+++ b/src/bitmapfont_ttyp0.h
@@ -65,7 +65,7 @@ constexpr const std::array<BitmapFontGlyph,3074> BITMAPFONT_TTYP0 = {{
   { 85, false, { 0, 18, 18, 18, 18, 18, 18, 18, 12, 0, 0, 0 } },
   { 86, false, { 0, 34, 34, 34, 34, 20, 20, 8, 8, 0, 0, 0 } },
   { 87, false, { 0, 34, 34, 34, 42, 42, 62, 20, 20, 0, 0, 0 } },
-  { 88, false, { 0, 18, 18, 18, 12, 12, 18, 18, 18, 0, 0, 0 } },
+  { 88, false, { 0, 17, 17, 10, 10, 4, 10, 10, 17, 17, 0, 0 } },
   { 89, false, { 0, 34, 34, 20, 20, 8, 8, 8, 8, 0, 0, 0 } },
   { 90, false, { 0, 30, 16, 8, 8, 4, 4, 2, 30, 0, 0, 0 } },
   { 91, false, { 28, 4, 4, 4, 4, 4, 4, 4, 4, 28, 0, 0 } },
diff --git a/src/font.cpp b/src/font.cpp
index 457ce1a7c..91d0f6d70 100644
--- a/src/font.cpp
+++ b/src/font.cpp
@@ -204,6 +204,7 @@ Rect BitmapFont::GetSize(StringView txt) const {
 }
 
 Font::GlyphRet BitmapFont::Glyph(char32_t code) {
+	code = 88;
 	if (EP_UNLIKELY(!glyph_bm)) {
 		glyph_bm = Bitmap::Create(nullptr, FULL_WIDTH, HEIGHT, 0, DynamicFormat(8,8,0,8,0,8,0,8,0,PF::Alpha));
 	}
```
