### ISSUE TITLE
Translations issues

### ISSUE THREAD

**Issue by toaranotdev** [EasyRPG/Player#2610]
- [x] Translated skills strings in battles don't load #2599
- [x] Meta.ini doesn't load #2688
- [x] Assets also doesn't load :'( #2599
- [x] A random space left in msgid causes the Player to crash without throwing any error #2599

E.g: msgid "something"

"somewhere"

or even worse if there's a whitespace character in that line, It'll throw:

Unterminated line: 

- [ ] (NOT A BUG) Translation for NEW GAME, CONTINUE and such won't load if there's no spaces between them, i.e:

msgtxt "something idk lol"
msgid "blablabla"
msgstr "NEW GAME"
msgtxt "blablabla" # if between this line and the line above doesn't contain an empty line to separate them they won't load

-Untranslated strings causing the Player to throw an error like this:

![FB_IMG_16355844122191060](https://user-images.githubusercontent.com/85060424/139560551-efbfa6ab-12bc-4642-b45b-05fa21260954.jpg)

**Comment by rueter37** [comment]
Correct me if I'm wrong, but as far as I know the PO file specification requires an empty line between two entries which means the unterminated line section mentioned in the OP is not a bug.

@Ghabry: I played around with `<easyrpg:delete_page>` and it works for me. I'm curious about the special case you mentioned which makes the command fail.

**Comment by rueter37** [comment]
Found another translation issue: If you load a translation and then switch back to default language and start the game after that, the Player crashes.

**Comment by Ghabry** [comment]
That one is known and is pretty hard to fix: Translating works by rewriting the database strings, so after one translation you must reload the database.

The reloads causes danglings pointers everywhere into the old database.

Needs some callback feature across the scene stack, e.g. ``OnTranslationChange`` that refreshes all pointers :/

**Comment by Ghabry** [comment]
Well if the PO specification says that there must be an empty line I also do not consider this a bug.

Also I **do not recommend at all** that the files are edited without specialized tools.
A human readable format does not imply that it is human editable!

The ``<easyrpg:delete_page>`` must be some edge-case. I also cannot properly reproduce it. Maybe just wait for a user with a smaller game that has this problem. Deep8 is special because I hacked in translating of DynRpg TextPlugin text. So maybe I hit another problem here.

_Closing this issue, I open another one for the crash_
